### ISSUE TITLE
@bind() decorator not working in IE11

### ISSUE THREAD

**Issue by davidrus** [developit/decko#8] opened 2017-03-06 12:20 UTC
I have this small example:

```javascript
import { Component, h, define } from 'skatejs';

import { bind } from 'decko';

export default class App extends Component<void> {
  static get is() { return 'my-app'; }

  @bind()
  handleClick() {
    console.log( 'clicked with this scope: ', this );
  }

  renderCallback() {
    return [
      <div onClick={this.handleClick}>Hello my lord!</div>,
    ];
  }
};

define(App);
```

When I try this in IE (11) I have this error: 
![image](https://cloud.githubusercontent.com/assets/1128128/23609529/c3d30442-026e-11e7-8668-00d08a49e704.png)

In chrome it works properly... 

You can try it in this repository which I created for this issue:
https://github.com/davidrus/skate-starter

**Comment by developit** [comment] 2017-03-06 15:44
@davidrus Seems like you're adding parens to the decorator, which is maybe causing the issue.
It should look like:

import { Component, h, define } from 'skatejs';

import { bind } from 'decko';

export default class App extends Component<void> {
  static get is() { return 'my-app'; }

  @bind
  handleClick() {
    console.log( 'clicked with this scope: ', this );
  }

  renderCallback() {
    return [
      <div onClick={this.handleClick}>Hello my lord!</div>,
    ];
  }
};

define(App);

**Comment by davidrus** [comment] 2017-03-07 08:53
Thank you for responce, but I tried it and still the same error.
I created codepen for it, so you can test it: http://codepen.io/davidrus/pen/vxXobW

**Comment by Hotell** [comment] 2017-03-07 10:33
Hey folks! so how it turns out problem is somewhere between skate and web-components polyfill.

With vanilla js decko works without problems

Demo:
http://codepen.io/Hotell/pen/bqwXmm?editors=1010

**Comment by Hotell** [comment] 2017-03-07 10:37
Gif or didn't happen right? :D 
![decko-bind-ie11](https://cloud.githubusercontent.com/assets/1223799/23652751/5b1c5496-032a-11e7-8c91-13a4984f718e.gif)

**Comment by Hotell** [comment] 2017-03-07 12:17
all right so after further investigation the issue is definitely with web component polyfills + skate.
cc @treshugart @azakus @justinfagnani

It can be fixed though on decko's side.

What's causing the trouble is getter you are creating and overriding ( ie calls it until it explodes )

![image](https://cloud.githubusercontent.com/assets/1223799/23655834/2ac2a298-0337-11e7-8350-917323753e42.png)


what can be done:
- redefine descriptor only with getter http://codepen.io/Hotell/pen/wJoaba?editors=1010
- make surer that original getter is invoked only once http://codepen.io/Hotell/pen/EWNaJy

check `myBind` function ( thas deckos bind redefined )

and ofc gif:
![decko-bind-ie11 wc-fix](https://cloud.githubusercontent.com/assets/1223799/23656027/36dc12d4-0338-11e7-8e99-c6c50abeb3dd.gif)

**Comment by developit** [comment] 2017-03-07 15:32
Hmm - that breaks caching though - the closure in `bind()` is scoped to the class definition, whereas `get()` is scoped to the instance.

I wonder though, why this is only being triggered from skate - maybe [this method](https://github.com/skatejs/skatejs/blob/master/src/util/get-own-property-descriptors.js#L5) is getting into an infinite loop because of the reassignment?

**Comment by treshugart** [comment] 2017-03-07 22:40
@Hotell I don't see how this is a problem with Skate.

To get around this, you could use http://babeljs.io/docs/plugins/transform-class-properties/ and just do:

```js
handleClick = () => {
  // this is now what you expect without explicit binding
}
```

**Comment by developit** [comment] 2017-03-08 00:51
@treshugart right, just we're talking about `@bind` as an alternative means of doing that.  Internally it's just this:

```js
function bind(target, key, desc) {
  let fn = desc.value;
  return {
    get() {
      // only bind to each instance on first access, then cache be replacing property descriptor
      let bound = fn.bind(this);
      Object.defineProperty(this, key, {
        value: bound
      });
      return bound;
    }
  };
}

class Foo extends Component {
  @bind
  handleClick(e) {
    this instanceof Foo;   // true
  }
  render() {
    return <div onClick={this.handleClick} />
                          // ^ binds here only on first render
  }
}
```

**Comment by Hotell** [comment] 2017-03-09 11:03
@treshugart 
> @Hotell I don't see how this is a problem with Skate. 

right sorry, wrong wording ( I didn't meant it's explicitly Skates fault ), but it's a possible culprit
 
> To get around this, you could use http://babeljs.io/docs/plugins/transform-class-properties/ and just do...

right it has one problem though:

if somebody does this ( I know within solid team with solid style guides this wont happen ever :) )

```js
class Foo {

 greeting = this.say
 sayWat = () => { return 'WAT' }
}
```

@developit 
> I checked and it seems like MDN actually recommends assigning a property instead of redefining it. Perhaps decko could switch to doing that.

Hmm interesting, didn't know about this "best practice" I personaly try to avoid `delete` but looks like it could be useful in here

**Comment by developit** [comment] 2017-03-09 16:01
I'm going to try out the simpler overwrite approach from that MDN page and we can check if that fixes the repro :)

**Comment by finico** [comment] 2017-12-05 19:34
@developit the solution can be found here https://github.com/andreypopp/autobind-decorator/blob/master/src/index.js#L68-L71

**Comment by developit** [comment] 2017-12-14 01:28
Nice - will have to add that lock.

**Comment by cronon** [comment] 2018-09-19 12:28
any progress?

**Comment by cronon** [comment] 2018-09-20 09:20
@developit please take a look https://github.com/developit/decko/pull/16

**Closed** 2018-10-12 22:30 UTC
Labels: bug, help wanted
